<?php

function env($constant, $default = null)
{
    return @constant($constant) ?? $default;
}

DEFINE('APP_URL', '');

/**
 * Base de Datos
 */
DEFINE('DB_HOST', '');
DEFINE('DB_PORT', '');

DEFINE('DB_DATABASE', '');
DEFINE('DB_BC_DATABASE', '');
DEFINE('DB_TIENDA_DATABASE', '');
DEFINE('DB_COMPLAINTS_DATABASE', '');

DEFINE('DB_USERNAME', '');
DEFINE('DB_PASSWORD', '');

DEFINE('DB_API_USERNAME', '');
DEFINE('DB_API_PASSWORD', '');

DEFINE('DB_TIENDA_USERNAME', '');
DEFINE('DB_TIENDA_PASSWORD', '');

DEFINE('TORITO_URL', '');
DEFINE('TORITO_PARTNER', '');
DEFINE('TORITO_SEED', '');

/**
 * Emails
 */
DEFINE('MAIL_SOPORTE_USER', '');
DEFINE('MAIL_SOPORTE_PASS', '');
DEFINE('MAIL_SOPORTE_NAME', '');

DEFINE('MAIL_LIQUIDACIONES_USER', '');
DEFINE('MAIL_LIQUIDACIONES_PASS', '');
DEFINE('MAIL_LIQUIDACIONES_NAME', '');

DEFINE('MAIL_GESTION_USER', '');
DEFINE('MAIL_GESTION_PASS', '');
DEFINE('MAIL_GESTION_NAME', '');


DEFINE('SOPORTE_V2_TOKEN', '');


DEFINE('TELEVENTAS_API_TOKEN', '');


DEFINE('ATSNACKS_TOKEN', '');

DEFINE('BUYAPOWA_API_BASE_URI', '');
DEFINE('BUYAPOWA_API_TOKEN', '');

DEFINE('TESORERIA_TOKEN', '');

//CALIMACO
#DEFINE('CALIMACO_TLS_URL','');
DEFINE('CALIMACO_TLS_URL', '');
DEFINE('CALIMACO_TLS_PASSWORD', '');

DEFINE('CALIMACO_RETAIL_URL', '');
DEFINE('CALIMACO_RETAIL_PASSWORD', '');

DEFINE('CALIMACO_RECARGAS_URL', '');
DEFINE('CALIMACO_RECARGAS_PASSWORD', '');

#PARA PRUEBAS DE CONTRATOS EN PRODUCCION SIN AFECTAR A LOS EMAIL VERDADEROS
DEFINE('SEND_EMAIL', '');
DEFINE('EMAIL_TEST', '');




DEFINE('AWS_SES_apuestatotal', '');

DEFINE('WEB_BIGDATA_HOST', '');
DEFINE('WEB_BIGDATA_USER', '');
DEFINE('WEB_BIGDATA_PASS', '');
DEFINE('WEB_BIGDATA_DB', '');


DEFINE('AWS_RDS_bc_apuestatotal_HOST', '');
DEFINE('AWS_RDS_bc_apuestatotal_USERNAME', '');
DEFINE('AWS_RDS_bc_apuestatotal_PASS', '');
DEFINE('AWS_RDS_bc_apuestatotal_DB', '');

DEFINE('MAIL_GESTION_NET_USER', 'AKIAX2ZAGCNPRXQSLQJ7');
DEFINE('MAIL_GESTION_NET_PASS', 'BCZ0rgxrWWPPcnvfMJZkNFLxi4jWs8Ts4S4/ZAYUmFBb');
DEFINE('MAIL_GESTION_NET_NAME', 'Gestion NET Apuesta Total');
DEFINE('MAIL_GESTION_NET_HOST', 'email-smtp.us-east-1.amazonaws.com');
DEFINE('MAIL_GESTION_NET_PORT', '587');
