<?php
include("db_connect.php");
include("sys_login.php");
require_once '/var/www/html/env.php';
require_once '/var/www/html/sys/helpers.php';
require_once '/var/www/html/sys/set_caja_notificacion.php';
cron_print_log('TEST para envio de correo NOTIFICACIÓN NO VENTA\n');
echo '<br>';
$test = (isset($_GET['test'])) ? "TEST" : env('SEND_EMAIL');
cron_print_log("Modo test: " . (($test === "TEST") ? "true" : "false") . "\n");
echo '<br>';
$body = "<div class='container'>";
$body .= '<table border="1" cellpadding="5" cellspacing="0" style="font-family: arial,serif" width="500px">';
$body .= '<thead>';
$body .= '<tr style="font-size: 16px; background-color:#395168; color: #fff">';
$body .= '<tr>';
$body .= '<th  colspan="2"  style="color: #fff; background-color: #395168; vertical-align: middle; font-size: 16px">';
$body .= 'READ AT Habich';
$body .= '</th>';
$body .= '</tr>';
$body .= '<tr>';
$body .= '<td style="color: #fff; background-color: #395168; vertical-align: middle; font-size: 16px">';
$body .= 'ID de caja';
$body .= '</td>';
$body .= '<td style="vertical-align: middle; font-size: 16px">';
$body .= '2008889';
$body .= '</td>';
$body .= '</tr>';
$body .= '<tr>';
$body .= '<td style="color: #fff; background-color: #395168; vertical-align: middle; font-size: 16px">';
$body .= 'Caja';
$body .= '</td>';
$body .= '<td style="vertical-align: middle; font-size: 16px">';
$body .= 'Caja 01';
$body .= '</td>';
$body .= '</tr>';
$body .= '<tr>';
$body .= '<td style="color: #fff; background-color: #395168; vertical-align: middle; font-size: 16px">';
$body .= 'Turno';
$body .= '</td>';
$body .= '<td style="vertical-align: middle; font-size: 16px">';
$body .= '1';
$body .= '</td>';
$body .= '</tr>';
$body .= '<tr>';
$body .= '<td style="color: #fff; background-color: #395168; vertical-align: middle; font-size: 16px">';
$body .= 'Fecha operación';
$body .= '</td>';
$body .= '<td style="vertical-align: middle; font-size: 16px">';
$body .= '2024-03-21';
$body .= '</td>';
$body .= '</tr>';
$body .= '<tr>';
$body .= '<td style="color: #fff; background-color: #395168; vertical-align: middle; font-size: 16px">';
$body .= 'Apertura';
$body .= '</td>';
$body .= '<td style="vertical-align: middle; font-size: 16px">';
$body .= '2024-03-21 13:01:50';
$body .= '</td>';
$body .= '</tr>';
$body .= '<tr>';
$body .= '<td style="color: #fff; background-color: #395168; vertical-align: middle; font-size: 16px">';
$body .= 'Cierre';
$body .= '</td>';
$body .= '<td style="vertical-align: middle; font-size: 16px">';
$body .= '2024-03-21 15:14:57';
$body .= '</td>';
$body .= '</tr>';
$body .= '</tbody>';
$body .= '</table>';
$body .= '</div>';

try {
    $resul = sendEmail_notificacionNoVenta($body, 'Read AT Habich', 'Luz Panijo', 'Golden Race', $test, 'Bingo');
    cron_print_log("Respuesta de envio de correo: " . (($resul) ? "'true'" : "'false'") . "\n");
    echo '<br>';
} catch (Exception $e) {
    cron_print_log($e->getMessage());
}
